export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  REQUEST_REFRESH: 'REQUEST_REFRESH',
  LOAD_REQUEST_FAIL: 'LOAD_REQUEST_FAIL',
  LOAD_REQUEST_SUCCESS: 'LOAD_REQUEST_SUCCESS',
  LOAD_MORE_REQUEST_FAIL: 'LOAD_MORE_REQUEST_FAIL',
  LOAD_MORE_REQUEST_SUCCESS: 'LOAD_MORE_REQUEST_SUCCESS',
};
